### PR TITLE
Feature/af networking support

### PR DESCRIPTION
**Pull request by cloforce**
-Removed SCHTTPRequest because it had some deprecation errors and swapped in AFNetworking and thus brought up the deployment target to 7.0 (97% users) requiring the NSAppTransportSecurity exception. Updated the readme to reflect this. Also renamed a few FSFood variable names to be in line with what the API calls them.

### CODE REVIEW

**Comment by pwightman** [comment]
Hi! I appreciate the pull request, but I won't accept this into the main repo for the same reason I described [in another PR](https://github.com/mysterioustrousers/FatSecretKit/pull/2#issuecomment-151026018). In short, for the purposes of this library, SVHTTPRequest should be replaced with NSURLSession, not AFNetworking.

I realize this library is currently broken since it uses SVHTTPRequest, and this pull request makes it work again, which I very much appreciate, but even so I can't accept it. If you'd like to switch it to use NSURLSession, feel free, but it's certainly not your responsibility as I imagine this is something that works well for your project and you have no obligation to meet my arbitrary "demands". Hopefully I can get around to fixing this myself soon!

**Comment by pwightman** [comment]
Fixed on master: https://github.com/mysterioustrousers/FatSecretKit/commit/3cd4d6afa5d4e066255e355d768a61180ad8c007

I'll push up a pod update in a bit.

**Comment by cloforce** [comment]
Awesome, I was just about to do it myself actually. Make sure you do a pod deintegrate and pod clean on the project and then manually remove the podfile. Cocoapods has a tendency to leave stuff lingering around. I believe that was your only pod.

Thanks for getting this started, really appreciate it.

**Comment by pwightman** [comment]
No problem! Thanks for the motivation ;-) I _think_ got all of cocoapods out, but it's pretty invasive so ¯_(ツ)_/¯. Also, I'm happy to accept the FSFood changes in a separate PR, I think that's a wise change.

**Comment by cloforce** [comment]
Sure, I don’t have much time to do it myself, but feel free to use it however you like. Good luck

**Pull request closed without merging**
